// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOP5bUAGtS_w77uWIccJK2zOFCIFHZPV0',
    appId: '1:248849438964:web:125234fd4145c48cd426a1',
    messagingSenderId: '248849438964',
    projectId: 'alex-calendar-ab9e7',
    authDomain: 'alex-calendar-ab9e7.firebaseapp.com',
    storageBucket: 'alex-calendar-ab9e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCioQdRbe9MiEMnfWjlI6woQGpsdCOGmIM',
    appId: '1:248849438964:android:1a58b08ce86ba895d426a1',
    messagingSenderId: '248849438964',
    projectId: 'alex-calendar-ab9e7',
    storageBucket: 'alex-calendar-ab9e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAie9W6J7ZY0xRKqfeVpwrr9A8yYOIXFq0',
    appId: '1:248849438964:ios:6c83ac1ec26d90a1d426a1',
    messagingSenderId: '248849438964',
    projectId: 'alex-calendar-ab9e7',
    storageBucket: 'alex-calendar-ab9e7.appspot.com',
    iosClientId: '248849438964-gqo1he3kmcu0o4ljbo8r5ngopu4cdn66.apps.googleusercontent.com',
    iosBundleId: 'com.alexcao.workspace.alexCalendar',
  );
}
